# Secret scanning configuration
# These paths contain intentional test/mock secrets for testing secret detection

paths-ignore:
  # Test files with mock API keys for testing redaction/safety features
  - "dashflow/crates/dashflow/src/self_improvement/redaction.rs"
  - "dashflow/crates/dashflow-observability/src/metrics.rs"
  - "codex_dashflow/crates/core/src/safety.rs"
  # Template files with placeholder values
  - "**/.env.template"
  - "**/.env.example"
  - "**/env.test.template"
  # Documentation with example patterns
  - "**/QUICKSTART.md"
  - "**/ROADMAP*.md"
  - "**/docs/**/*.md"
  - "**/examples/*.toml"
